// Flat config. Recommended presets only: a bespoke rule set would be a second
// opinion to maintain for no benefit. The floor is "lint runs and can fail", not "lint encodes
// taste".
import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    // dist/ is generated by `tsc`; demo/dist/ by esbuild for the visual check.
    ignores: ["dist/**", "demo/dist/**", "node_modules/**"],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ["**/*.ts", "**/*.tsx"],
    // Client islands touch browser APIs; the parser and server components
    // run under Node. Both global sets, one config.
    languageOptions: { globals: { ...globals.node, ...globals.browser } },
  },
  {
    // Tests are plain Node running under `node --test`.
    files: ["test/**/*.js", "test/**/*.mjs"],
    // browser.mjs is Node driving a browser: page.evaluate bodies run there.
    languageOptions: { globals: { ...globals.node, ...globals.nodeBuiltin, ...globals.browser } },
  },
);
